repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 19b28a9f0a0102b30776f054bea4176e7af50dbe    # frozen: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
  - id: pretty-format-toml
    args:
    - --autofix

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.15
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: .venv/bin/mypy
    language: system
    types: [python]
    require_serial: true

  - id: ty
    name: ty
    entry: .venv/bin/ty check
    language: system
    types: [python]
    require_serial: true
    pass_filenames: false
    args: [src]

  - id: pytest
    name: pytest
    entry: .venv/bin/pytest
    language: system
    pass_filenames: false
    always_run: true
